program: 'training.task'
method: 'grid'
metric:
  name: 'eval_accuracy'
  goal: 'maximize'

parameters:
  model:
    values: ['clip', 'vilt']
  batch_size:
    values: [16, 32, 64]
  lr:
    values: [0.00001, 0.0001, 0.001]
  epochs:
    values: [5, 10, 15]
  text_fname:
    values: ['texts_v2.json']
